-- Obsiddy phase 4 — give the connection sweep a rotating cursor.
--
-- ⚠️ HAND-EDITED. Do not regenerate. ⚠️
--
-- `prisma migrate dev --create-only` again emitted nine destructive statements
-- around the one real change, for the same reason as every other migration on
-- these tables: Prisma cannot model generated columns, HNSW indexes, or an FK
-- into a Sunrise-owned model, so it reads all of them as drift on every diff.
-- Removed, and listed so the next person can tell "deliberately dropped" from
-- "forgotten":
--
--   ALTER TABLE "framework_obsiddy_space"                       -- B1: the GDPR
--     DROP CONSTRAINT "framework_obsiddy_space_userId_fkey";    --     cascade FK
--   DROP INDEX "idx_ai_knowledge_chunk_search_vector";          -- baseline A2
--   DROP INDEX "idx_knowledge_embedding";                       -- baseline A3
--   DROP INDEX "idx_message_embedding";                         -- baseline A4
--   DROP INDEX "idx_framework_obsiddy_embedding_hnsw";          -- B3
--   DROP INDEX "idx_framework_obsiddy_embedding_search_vector"; -- B7
--   DROP INDEX "idx_framework_obsiddy_task_search_vector";      -- B5
--   ALTER TABLE "ai_knowledge_chunk"     ALTER COLUMN "searchVector" DROP DEFAULT;
--   ALTER TABLE "framework_obsiddy_task" ALTER COLUMN "searchVector" DROP DEFAULT;
--
-- **Note the shape of the last one.** Prisma folded
-- `ALTER COLUMN "searchVector" DROP DEFAULT` into the SAME statement as the
-- wanted `ADD COLUMN`, so this one could not be dropped wholesale — it had to be
-- split. That is the most dangerous form this footgun takes: a destructive clause
-- riding along inside a statement you do want. Read every generated line, not
-- just the ones with DROP at the start.
--
-- `npm run db:drift-check` after applying. Non-negotiable.

-- ─── The one change this migration makes ─────────────────────────────────────

-- Nullable, no backfill: null means "never swept" and sorts first, so every
-- existing row is treated as due on the next sweep.
ALTER TABLE "framework_obsiddy_embedding" ADD COLUMN "sweptAt" TIMESTAMP(3);
